language: php

php:
  - 5.5
  - 5.6
  - 7.0

branches:
  only:
    - master
    - travis

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - mkdir -p tests/tmp
  - mkdir -p build/logs/

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - php vendor/bin/coveralls -x coverage.clover
